CREATE TABLE seller_onboarding (
    id INT AUTO_INCREMENT PRIMARY KEY,
    seller_email VARCHAR(255),
    shop_name VARCHAR(255) NOT NULL,
    country VARCHAR(100) NOT NULL,
    state VARCHAR(100) NOT NULL,
    postal_code VARCHAR(20) NOT NULL,
    address1 VARCHAR(255) NOT NULL,
    address2 VARCHAR(255),
    city VARCHAR(100) NOT NULL,
    phone VARCHAR(50) NOT NULL,
    logo_path VARCHAR(255),
    aspect_ratio VARCHAR(20),
    has_inventory BOOLEAN,
    inventory_file VARCHAR(255),
    include_drafts BOOLEAN,
    made_to_order BOOLEAN,
    integration_access BOOLEAN,
    shipping_option VARCHAR(50),
    fixed_rate_cost DECIMAL(10,2),
    free_ship_threshold DECIMAL(10,2),
    package_size VARCHAR(20),
    offer_pickup BOOLEAN,
    return_days INT DEFAULT 12,
    cancel_days INT DEFAULT 3,
    call_scheduled BOOLEAN,
    description TEXT,
    badges VARCHAR(255),
    facebook VARCHAR(255),
    instagram VARCHAR(255),
    pinterest VARCHAR(255),
    completed BOOLEAN DEFAULT 0,
    skipped_optional BOOLEAN,
    submission_dt DATETIME,
    progress INT DEFAULT 0
);
